version: '3'
services:
  db:
    image: postgres:15.2
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: sa_password
      POSTGRES_DB: postgres
    networks:
      - pleasanter-net

  codedefiner:
    image: implem/pleasanter:codedefiner
    depends_on:
      - db
    env_file: env-list
    networks:
      - pleasanter-net
    command: _rds

  pleasanter:
    image: implem/pleasanter:1.3.40.1
    depends_on:
      - db
      - codedefiner
    env_file: env-list
    ports:
      - 50001:80
    networks:
      - pleasanter-net

networks:
  pleasanter-net:

volumes:
  db-data:
