version: '3'

services:
  db:
    container_name: postgres
    image: postgres:15
    volumes:
      - type: bind
        source: ./initdb
        target: /docker-entrypoint-initdb.d
      - type: volume
        source: db-data
        target: /var/lib/postgresql/data
      - type: bind
        source: /<path to your work dir>/backup/
        target: /backup
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - POSTGRES_HOST_AUTH_METHOD
      - POSTGRES_INITDB_ARGS
    networks:
      - pleasanter-net

  codedefiner:
    container_name: codedefiner
    image: implem/pleasanter:codedefiner
    depends_on:
      - db
    environment:
      Implem.Pleasanter_Rds_PostgreSQL_SaConnectionString: ${Implem_Pleasanter_Rds_PostgreSQL_SaConnectionString}
      Implem.Pleasanter_Rds_PostgreSQL_OwnerConnectionString: ${Implem_Pleasanter_Rds_PostgreSQL_OwnerConnectionString}
      Implem.Pleasanter_Rds_PostgreSQL_UserConnectionString: ${Implem_Pleasanter_Rds_PostgreSQL_UserConnectionString}
    networks:
      - pleasanter-net
    command: _rds

  pleasanter:
    container_name: pleasanter
    image: implem/pleasanter
    depends_on:
      - db
    environment:
      Implem.Pleasanter_Rds_PostgreSQL_SaConnectionString: ${Implem_Pleasanter_Rds_PostgreSQL_SaConnectionString}
      Implem.Pleasanter_Rds_PostgreSQL_OwnerConnectionString: ${Implem_Pleasanter_Rds_PostgreSQL_OwnerConnectionString}
      Implem.Pleasanter_Rds_PostgreSQL_UserConnectionString: ${Implem_Pleasanter_Rds_PostgreSQL_UserConnectionString}
    ports:
      - 50001:80
    networks:
      - pleasanter-net

networks:
  pleasanter-net:

volumes:
  db-data:
